// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/tasks/v2/catalog.pub.proto (package anduril.tasks.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/tasks/v2/catalog.pub.proto.
 */
export const file_anduril_tasks_v2_catalog_pub = /*@__PURE__*/
  fileDesc("CiJhbmR1cmlsL3Rhc2tzL3YyL2NhdGFsb2cucHViLnByb3RvEhBhbmR1cmlsLnRhc2tzLnYyIk8KC1Rhc2tDYXRhbG9nEjoKEHRhc2tfZGVmaW5pdGlvbnMYASADKAsyIC5hbmR1cmlsLnRhc2tzLnYyLlRhc2tEZWZpbml0aW9uSgQIAhADIkYKDlRhc2tEZWZpbml0aW9uEh4KFnRhc2tfc3BlY2lmaWNhdGlvbl91cmwYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJQsgBChRjb20uYW5kdXJpbC50YXNrcy52MkIPQ2F0YWxvZ1B1YlByb3RvUAFaPWdoZS5hbmR1cmlsLmRldi9hbmR1cmlsL2FuZHVyaWxhcGlzLWdvL2FuZHVyaWwvdGFza3MvdjI7dGFza3OiAgNBVFiqAhBBbmR1cmlsLlRhc2tzLlYyygIQQW5kdXJpbFxUYXNrc1xWMuICHEFuZHVyaWxcVGFza3NcVjJcR1BCTWV0YWRhdGHqAhJBbmR1cmlsOjpUYXNrczo6VjJiBnByb3RvMw");

/**
 * Describes the message anduril.tasks.v2.TaskCatalog.
 * Use `create(TaskCatalogSchema)` to create a new message.
 */
export const TaskCatalogSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_catalog_pub, 0);

/**
 * Describes the message anduril.tasks.v2.TaskDefinition.
 * Use `create(TaskDefinitionSchema)` to create a new message.
 */
export const TaskDefinitionSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_catalog_pub, 1);

