// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/tasks/v2/objective.pub.proto (package anduril.tasks.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_type_coords_pub } from "../../type/coords.pub_pb.js";

/**
 * Describes the file anduril/tasks/v2/objective.pub.proto.
 */
export const file_anduril_tasks_v2_objective_pub = /*@__PURE__*/
  fileDesc("CiRhbmR1cmlsL3Rhc2tzL3YyL29iamVjdGl2ZS5wdWIucHJvdG8SEGFuZHVyaWwudGFza3MudjIiXQoJT2JqZWN0aXZlEhMKCWVudGl0eV9pZBgBIAEoCUgAEigKBXBvaW50GAUgASgLMhcuYW5kdXJpbC50YXNrcy52Mi5Qb2ludEgAQgsKCW9iamVjdGl2ZUoECAIQAyJaCgVQb2ludBIWCg5yZWZlcmVuY2VfbmFtZRgBIAEoCRIeCgNsbGEYAiABKAsyES5hbmR1cmlsLnR5cGUuTExBEhkKEWJhY2tpbmdfZW50aXR5X2lkGAMgASgJQsoBChRjb20uYW5kdXJpbC50YXNrcy52MkIRT2JqZWN0aXZlUHViUHJvdG9QAVo9Z2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC90YXNrcy92Mjt0YXNrc6ICA0FUWKoCEEFuZHVyaWwuVGFza3MuVjLKAhBBbmR1cmlsXFRhc2tzXFYy4gIcQW5kdXJpbFxUYXNrc1xWMlxHUEJNZXRhZGF0YeoCEkFuZHVyaWw6OlRhc2tzOjpWMmIGcHJvdG8z", [file_anduril_type_coords_pub]);

/**
 * Describes the message anduril.tasks.v2.Objective.
 * Use `create(ObjectiveSchema)` to create a new message.
 */
export const ObjectiveSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_objective_pub, 0);

/**
 * Describes the message anduril.tasks.v2.Point.
 * Use `create(PointSchema)` to create a new message.
 */
export const PointSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_objective_pub, 1);

