// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/taskmanager/v1/generic_spec.pub.proto (package anduril.taskmanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/taskmanager/v1/generic_spec.pub.proto.
 */
export const file_anduril_taskmanager_v1_generic_spec_pub = /*@__PURE__*/
  fileDesc("Ci1hbmR1cmlsL3Rhc2ttYW5hZ2VyL3YxL2dlbmVyaWNfc3BlYy5wdWIucHJvdG8SFmFuZHVyaWwudGFza21hbmFnZXIudjEiNgoLR2VuZXJpY1NwZWMSJwoHcGF5bG9hZBgBIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZUL2AQoaY29tLmFuZHVyaWwudGFza21hbmFnZXIudjFCE0dlbmVyaWNTcGVjUHViUHJvdG9QAVpJZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC90YXNrbWFuYWdlci92MTt0YXNrbWFuYWdlcqICA0FUWKoCFkFuZHVyaWwuVGFza21hbmFnZXIuVjHKAhZBbmR1cmlsXFRhc2ttYW5hZ2VyXFYx4gIiQW5kdXJpbFxUYXNrbWFuYWdlclxWMVxHUEJNZXRhZGF0YeoCGEFuZHVyaWw6OlRhc2ttYW5hZ2VyOjpWMWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * Describes the message anduril.taskmanager.v1.GenericSpec.
 * Use `create(GenericSpecSchema)` to create a new message.
 */
export const GenericSpecSchema = /*@__PURE__*/
  messageDesc(file_anduril_taskmanager_v1_generic_spec_pub, 0);

