// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/tasks/v2/shared/maneuver.pub.proto (package anduril.tasks.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_tasks_v2_objective_pub } from "../objective.pub_pb.js";
import { file_anduril_tasks_v2_shared_isr_pub } from "./isr.pub_pb.js";

/**
 * Describes the file anduril/tasks/v2/shared/maneuver.pub.proto.
 */
export const file_anduril_tasks_v2_shared_maneuver_pub = /*@__PURE__*/
  fileDesc("CiphbmR1cmlsL3Rhc2tzL3YyL3NoYXJlZC9tYW5ldXZlci5wdWIucHJvdG8SEGFuZHVyaWwudGFza3MudjIiOQoHTWFyc2hhbBIuCglvYmplY3RpdmUYASABKAsyGy5hbmR1cmlsLnRhc2tzLnYyLk9iamVjdGl2ZSI0CgdUcmFuc2l0EikKBHBsYW4YASABKAsyGy5hbmR1cmlsLnRhc2tzLnYyLlJvdXRlUGxhbiIzCglSb3V0ZVBsYW4SJgoFcm91dGUYASABKAsyFy5hbmR1cmlsLnRhc2tzLnYyLlJvdXRlIjQKBVJvdXRlEisKBHBhdGgYASADKAsyHS5hbmR1cmlsLnRhc2tzLnYyLlBhdGhTZWdtZW50InYKC1BhdGhTZWdtZW50Ei4KCHdheXBvaW50GAEgASgLMhouYW5kdXJpbC50YXNrcy52Mi5XYXlwb2ludEgAEioKBmxvaXRlchgCIAEoCzIYLmFuZHVyaWwudGFza3MudjIuTG9pdGVySABCCwoJZW5kX3BvaW50IkEKCFdheXBvaW50EiwKCWxsYV9wb2ludBgBIAEoCzIXLmFuZHVyaWwudGFza3MudjIuUG9pbnRIAEIHCgVwb2ludCJ4Cg5TZXRMYXVuY2hSb3V0ZRIpCgRwbGFuGAEgASgLMhsuYW5kdXJpbC50YXNrcy52Mi5Sb3V0ZVBsYW4SOwoNdHJhY2tpbmdfbW9kZRgCIAEoDjIkLmFuZHVyaWwudGFza3MudjIuTGF1bmNoVHJhY2tpbmdNb2RlKosBChJMYXVuY2hUcmFja2luZ01vZGUSIAocTEFVTkNIX1RSQUNLSU5HX01PREVfSU5WQUxJRBAAEicKI0xBVU5DSF9UUkFDS0lOR19NT0RFX0dPX1RPX1dBWVBPSU5UEAESKgomTEFVTkNIX1RSQUNLSU5HX01PREVfVFJBQ0tfVE9fV0FZUE9JTlQQAkLJAQoUY29tLmFuZHVyaWwudGFza3MudjJCEE1hbmV1dmVyUHViUHJvdG9QAVo9Z2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC90YXNrcy92Mjt0YXNrc6ICA0FUWKoCEEFuZHVyaWwuVGFza3MuVjLKAhBBbmR1cmlsXFRhc2tzXFYy4gIcQW5kdXJpbFxUYXNrc1xWMlxHUEJNZXRhZGF0YeoCEkFuZHVyaWw6OlRhc2tzOjpWMmIGcHJvdG8z", [file_anduril_tasks_v2_objective_pub, file_anduril_tasks_v2_shared_isr_pub]);

/**
 * Describes the message anduril.tasks.v2.Marshal.
 * Use `create(MarshalSchema)` to create a new message.
 */
export const MarshalSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 0);

/**
 * Describes the message anduril.tasks.v2.Transit.
 * Use `create(TransitSchema)` to create a new message.
 */
export const TransitSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 1);

/**
 * Describes the message anduril.tasks.v2.RoutePlan.
 * Use `create(RoutePlanSchema)` to create a new message.
 */
export const RoutePlanSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 2);

/**
 * Describes the message anduril.tasks.v2.Route.
 * Use `create(RouteSchema)` to create a new message.
 */
export const RouteSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 3);

/**
 * Describes the message anduril.tasks.v2.PathSegment.
 * Use `create(PathSegmentSchema)` to create a new message.
 */
export const PathSegmentSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 4);

/**
 * Describes the message anduril.tasks.v2.Waypoint.
 * Use `create(WaypointSchema)` to create a new message.
 */
export const WaypointSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 5);

/**
 * Describes the message anduril.tasks.v2.SetLaunchRoute.
 * Use `create(SetLaunchRouteSchema)` to create a new message.
 */
export const SetLaunchRouteSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_shared_maneuver_pub, 6);

/**
 * Describes the enum anduril.tasks.v2.LaunchTrackingMode.
 */
export const LaunchTrackingModeSchema = /*@__PURE__*/
  enumDesc(file_anduril_tasks_v2_shared_maneuver_pub, 0);

/**
 * @generated from enum anduril.tasks.v2.LaunchTrackingMode
 */
export const LaunchTrackingMode = /*@__PURE__*/
  tsEnum(LaunchTrackingModeSchema);

