// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/classification.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/entitymanager/v1/classification.pub.proto.
 */
export const file_anduril_entitymanager_v1_classification_pub = /*@__PURE__*/
  fileDesc("CjFhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvY2xhc3NpZmljYXRpb24ucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEi4wEKDkNsYXNzaWZpY2F0aW9uEkEKBWxldmVsGAEgASgOMi4uYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkNsYXNzaWZpY2F0aW9uTGV2ZWxzQgIYARJECgdkZWZhdWx0GAIgASgLMjMuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkNsYXNzaWZpY2F0aW9uSW5mb3JtYXRpb24SSAoGZmllbGRzGAMgAygLMjguYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkZpZWxkQ2xhc3NpZmljYXRpb25JbmZvcm1hdGlvbiKNAQoeRmllbGRDbGFzc2lmaWNhdGlvbkluZm9ybWF0aW9uEhIKCmZpZWxkX3BhdGgYASABKAkSVwoaY2xhc3NpZmljYXRpb25faW5mb3JtYXRpb24YAiABKAsyMy5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuQ2xhc3NpZmljYXRpb25JbmZvcm1hdGlvbiJrChlDbGFzc2lmaWNhdGlvbkluZm9ybWF0aW9uEj0KBWxldmVsGAEgASgOMi4uYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkNsYXNzaWZpY2F0aW9uTGV2ZWxzEg8KB2NhdmVhdHMYAiADKAkqhAIKFENsYXNzaWZpY2F0aW9uTGV2ZWxzEiEKHUNMQVNTSUZJQ0FUSU9OX0xFVkVMU19JTlZBTElEEAASJgoiQ0xBU1NJRklDQVRJT05fTEVWRUxTX1VOQ0xBU1NJRklFRBABEjEKLUNMQVNTSUZJQ0FUSU9OX0xFVkVMU19DT05UUk9MTEVEX1VOQ0xBU1NJRklFRBACEiYKIkNMQVNTSUZJQ0FUSU9OX0xFVkVMU19DT05GSURFTlRJQUwQAxIgChxDTEFTU0lGSUNBVElPTl9MRVZFTFNfU0VDUkVUEAQSJAogQ0xBU1NJRklDQVRJT05fTEVWRUxTX1RPUF9TRUNSRVQQBUKHAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIWQ2xhc3NpZmljYXRpb25QdWJQcm90b1ABWk1naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjE7ZW50aXR5bWFuYWdlcqICA0FFWKoCGEFuZHVyaWwuRW50aXR5bWFuYWdlci5WMcoCGEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMeICJEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMVxHUEJNZXRhZGF0YeoCGkFuZHVyaWw6OkVudGl0eW1hbmFnZXI6OlYxYgZwcm90bzM");

/**
 * Describes the message anduril.entitymanager.v1.Classification.
 * Use `create(ClassificationSchema)` to create a new message.
 */
export const ClassificationSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_classification_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.FieldClassificationInformation.
 * Use `create(FieldClassificationInformationSchema)` to create a new message.
 */
export const FieldClassificationInformationSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_classification_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.ClassificationInformation.
 * Use `create(ClassificationInformationSchema)` to create a new message.
 */
export const ClassificationInformationSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_classification_pub, 2);

/**
 * Describes the enum anduril.entitymanager.v1.ClassificationLevels.
 */
export const ClassificationLevelsSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_classification_pub, 0);

/**
 * An enumeration of security classification levels.
 *
 * @generated from enum anduril.entitymanager.v1.ClassificationLevels
 */
export const ClassificationLevels = /*@__PURE__*/
  tsEnum(ClassificationLevelsSchema);

