// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/classification.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/classification.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_classification_pub: GenFile;

/**
 * A component that describes an entity's security classification levels.
 *
 * @generated from message anduril.entitymanager.v1.Classification
 */
export declare type Classification = Message<"anduril.entitymanager.v1.Classification"> & {
  /**
   * The default classification information which should be assumed to apply to everything in
   * the entity unless a specific field level classification is present.
   *
   * @generated from field: anduril.entitymanager.v1.ClassificationInformation default = 2;
   */
  default?: ClassificationInformation;

  /**
   * The set of individual field classification information which should always precedence
   * over the default classification information.
   *
   * @generated from field: repeated anduril.entitymanager.v1.FieldClassificationInformation fields = 3;
   */
  fields: FieldClassificationInformation[];
};

/**
 * Describes the message anduril.entitymanager.v1.Classification.
 * Use `create(ClassificationSchema)` to create a new message.
 */
export declare const ClassificationSchema: GenMessage<Classification>;

/**
 * A field specific classification information definition.
 *
 * @generated from message anduril.entitymanager.v1.FieldClassificationInformation
 */
export declare type FieldClassificationInformation = Message<"anduril.entitymanager.v1.FieldClassificationInformation"> & {
  /**
   * Proto field path which is the string representation of a field.
   * > example: signal.bandwidth_hz would be bandwidth_hz in the signal component
   *
   * @generated from field: string field_path = 1;
   */
  fieldPath: string;

  /**
   * The information which makes up the field level classification marking.
   *
   * @generated from field: anduril.entitymanager.v1.ClassificationInformation classification_information = 2;
   */
  classificationInformation?: ClassificationInformation;
};

/**
 * Describes the message anduril.entitymanager.v1.FieldClassificationInformation.
 * Use `create(FieldClassificationInformationSchema)` to create a new message.
 */
export declare const FieldClassificationInformationSchema: GenMessage<FieldClassificationInformation>;

/**
 * Represents all of the necessary information required to generate a summarized
 * classification marking.
 *
 * > example: A summarized classification marking of "TOPSECRET//NOFORN//FISA"
 *            would be defined as: { "level": 5, "caveats": [ "NOFORN, "FISA" ] }
 *
 * @generated from message anduril.entitymanager.v1.ClassificationInformation
 */
export declare type ClassificationInformation = Message<"anduril.entitymanager.v1.ClassificationInformation"> & {
  /**
   * Classification level to be applied to the information in question.
   *
   * @generated from field: anduril.entitymanager.v1.ClassificationLevels level = 1;
   */
  level: ClassificationLevels;

  /**
   * Caveats that may further restrict how the information can be disseminated.
   *
   * @generated from field: repeated string caveats = 2;
   */
  caveats: string[];
};

/**
 * Describes the message anduril.entitymanager.v1.ClassificationInformation.
 * Use `create(ClassificationInformationSchema)` to create a new message.
 */
export declare const ClassificationInformationSchema: GenMessage<ClassificationInformation>;

/**
 * An enumeration of security classification levels.
 *
 * @generated from enum anduril.entitymanager.v1.ClassificationLevels
 */
export enum ClassificationLevels {
  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_UNCLASSIFIED = 1;
   */
  UNCLASSIFIED = 1,

  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_CONTROLLED_UNCLASSIFIED = 2;
   */
  CONTROLLED_UNCLASSIFIED = 2,

  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_CONFIDENTIAL = 3;
   */
  CONFIDENTIAL = 3,

  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_SECRET = 4;
   */
  SECRET = 4,

  /**
   * @generated from enum value: CLASSIFICATION_LEVELS_TOP_SECRET = 5;
   */
  TOP_SECRET = 5,
}

/**
 * Describes the enum anduril.entitymanager.v1.ClassificationLevels.
 */
export declare const ClassificationLevelsSchema: GenEnum<ClassificationLevels>;

