// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/contact_details.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/contact_details.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_contact_details_pub: GenFile;

/**
 * Contains details on how to make contact with an entity.
 *
 * @generated from message anduril.entitymanager.v1.ContactDetails
 */
export declare type ContactDetails = Message<"anduril.entitymanager.v1.ContactDetails"> & {
  /**
   * The primary phone number for this entity.
   *
   * @generated from field: string phone_number = 1;
   */
  phoneNumber: string;
};

/**
 * Describes the message anduril.entitymanager.v1.ContactDetails.
 * Use `create(ContactDetailsSchema)` to create a new message.
 */
export declare const ContactDetailsSchema: GenMessage<ContactDetails>;

