// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/contact_details.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/entitymanager/v1/contact_details.pub.proto.
 */
export const file_anduril_entitymanager_v1_contact_details_pub = /*@__PURE__*/
  fileDesc("CjJhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvY29udGFjdF9kZXRhaWxzLnB1Yi5wcm90bxIYYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxIiYKDkNvbnRhY3REZXRhaWxzEhQKDHBob25lX251bWJlchgBIAEoCUKHAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIWQ29udGFjdERldGFpbHNQdWJQcm90b1ABWk1naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjE7ZW50aXR5bWFuYWdlcqICA0FFWKoCGEFuZHVyaWwuRW50aXR5bWFuYWdlci5WMcoCGEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMeICJEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMVxHUEJNZXRhZGF0YeoCGkFuZHVyaWw6OkVudGl0eW1hbmFnZXI6OlYxYgZwcm90bzM");

/**
 * Describes the message anduril.entitymanager.v1.ContactDetails.
 * Use `create(ContactDetailsSchema)` to create a new message.
 */
export const ContactDetailsSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_contact_details_pub, 0);

