// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/correlations.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/correlations.pub.proto.
 */
export const file_anduril_entitymanager_v1_correlations_pub = /*@__PURE__*/
  fileDesc("Ci9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvY29ycmVsYXRpb25zLnB1Yi5wcm90bxIYYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxItIBCgpDb3JyZWxhdGVkEhkKEXByaW1hcnlfZW50aXR5X2lkGAEgASgJEjsKBnN0YXR1cxgCIAEoDjIrLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5Db3JyZWxhdGlvblN0YXR1cxI6CgZzY29yZXMYAyADKAsyKi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuQ29ycmVsYXRpb25TY29yZRIwCgxleHBpcmVzX3RpbWUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIuIBChBDb3JyZWxhdGlvblNjb3JlEhcKD290aGVyX2VudGl0eV9pZBgBIAEoCRINCgVzY29yZRgCIAEoAhJFCg5pbnRlcnByZXRhdGlvbhgDIAEoDjItLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5TY29yZUludGVycHJldGF0aW9uEhwKEGxpbmsxNl9jb21wbGlhbnQYBCABKAhCAhgBEkEKDG90aGVyX3N0YXR1cxgFIAEoDjIrLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5Db3JyZWxhdGlvblN0YXR1cyrxAQoRQ29ycmVsYXRpb25TdGF0dXMSHgoaQ09SUkVMQVRJT05fU1RBVFVTX0lOVkFMSUQQABIoCiRDT1JSRUxBVElPTl9TVEFUVVNfTUFOVUFMX0lOU1BFQ1RJT04QARIlCiFDT1JSRUxBVElPTl9TVEFUVVNfQVVUT19TVUdHRVNURUQQAhIqCiJDT1JSRUxBVElPTl9TVEFUVVNfU1RBUlRfQ09SUkVMQVRFEAMaAggBEiAKHENPUlJFTEFUSU9OX1NUQVRVU19DT05GSVJNRUQQBBIdChlDT1JSRUxBVElPTl9TVEFUVVNfREVOSUVEEAUqoQEKE1Njb3JlSW50ZXJwcmV0YXRpb24SIAocU0NPUkVfSU5URVJQUkVUQVRJT05fSU5WQUxJRBAAEiEKHVNDT1JFX0lOVEVSUFJFVEFUSU9OX1VOTElLRUxZEAESHwobU0NPUkVfSU5URVJQUkVUQVRJT05fTElLRUxZEAISJAogU0NPUkVfSU5URVJQUkVUQVRJT05fVkVSWV9MSUtFTFkQA0KFAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIUQ29ycmVsYXRpb25zUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message anduril.entitymanager.v1.Correlated.
 * Use `create(CorrelatedSchema)` to create a new message.
 */
export const CorrelatedSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_correlations_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.CorrelationScore.
 * Use `create(CorrelationScoreSchema)` to create a new message.
 */
export const CorrelationScoreSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_correlations_pub, 1);

/**
 * Describes the enum anduril.entitymanager.v1.CorrelationStatus.
 */
export const CorrelationStatusSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_correlations_pub, 0);

/**
 * The status of the correlation.
 *
 * @generated from enum anduril.entitymanager.v1.CorrelationStatus
 */
export const CorrelationStatus = /*@__PURE__*/
  tsEnum(CorrelationStatusSchema);

/**
 * Describes the enum anduril.entitymanager.v1.ScoreInterpretation.
 */
export const ScoreInterpretationSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_correlations_pub, 1);

/**
 * The interpretation of the correlation score.
 *
 * @generated from enum anduril.entitymanager.v1.ScoreInterpretation
 */
export const ScoreInterpretation = /*@__PURE__*/
  tsEnum(ScoreInterpretationSchema);

