// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/filter_dynamic.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_filter_pub } from "./filter.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/filter_dynamic.pub.proto.
 */
export const file_anduril_entitymanager_v1_filter_dynamic_pub = /*@__PURE__*/
  fileDesc("CjFhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvZmlsdGVyX2R5bmFtaWMucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEixAEKEER5bmFtaWNTdGF0ZW1lbnQSMwoGZmlsdGVyGAEgASgLMiMuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlN0YXRlbWVudBI1CghzZWxlY3RvchgCIAEoCzIjLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5TdGF0ZW1lbnQSRAoKY29tcGFyYXRvchgDIAEoCzIwLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5JbnRlcnNlY3Rpb25Db21wYXJhdG9yIm8KFkludGVyc2VjdGlvbkNvbXBhcmF0b3ISRwoRd2l0aGluX2NvbXBhcmlzb24YASABKAsyKi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuV2l0aGluQ29tcGFyaXNvbkgAQgwKCmNvbXBhcmlzb24iEgoQV2l0aGluQ29tcGFyaXNvbkKGAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIVRmlsdGVyRHluYW1pY1B1YlByb3RvUAFaTWdoZS5hbmR1cmlsLmRldi9hbmR1cmlsL2FuZHVyaWxhcGlzLWdvL2FuZHVyaWwvZW50aXR5bWFuYWdlci92MTtlbnRpdHltYW5hZ2VyogIDQUVYqgIYQW5kdXJpbC5FbnRpdHltYW5hZ2VyLlYxygIYQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYx4gIkQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYxXEdQQk1ldGFkYXRh6gIaQW5kdXJpbDo6RW50aXR5bWFuYWdlcjo6VjFiBnByb3RvMw", [file_anduril_entitymanager_v1_filter_pub]);

/**
 * Describes the message anduril.entitymanager.v1.DynamicStatement.
 * Use `create(DynamicStatementSchema)` to create a new message.
 */
export const DynamicStatementSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_filter_dynamic_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.IntersectionComparator.
 * Use `create(IntersectionComparatorSchema)` to create a new message.
 */
export const IntersectionComparatorSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_filter_dynamic_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.WithinComparison.
 * Use `create(WithinComparisonSchema)` to create a new message.
 */
export const WithinComparisonSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_filter_dynamic_pub, 2);

