// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/group.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/group.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_group_pub: GenFile;

/**
 * Details related to grouping for this entity
 *
 * @generated from message anduril.entitymanager.v1.GroupDetails
 */
export declare type GroupDetails = Message<"anduril.entitymanager.v1.GroupDetails"> & {
  /**
   * @generated from oneof anduril.entitymanager.v1.GroupDetails.group_type
   */
  groupType: {
    /**
     * @generated from field: anduril.entitymanager.v1.Team team = 1;
     */
    value: Team;
    case: "team";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.Echelon echelon = 3;
     */
    value: Echelon;
    case: "echelon";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message anduril.entitymanager.v1.GroupDetails.
 * Use `create(GroupDetailsSchema)` to create a new message.
 */
export declare const GroupDetailsSchema: GenMessage<GroupDetails>;

/**
 * Describes a Team group type. Comprised of autonomous entities where an entity
 * in a Team can only be a part of a single Team at a time.
 *
 * @generated from message anduril.entitymanager.v1.Team
 */
export declare type Team = Message<"anduril.entitymanager.v1.Team"> & {
};

/**
 * Describes the message anduril.entitymanager.v1.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export declare const TeamSchema: GenMessage<Team>;

/**
 * Describes a Echelon group type.  Comprised of entities which are members of the
 * same unit or echelon. Ex: A group of tanks within a armored company or that same company
 * as a member of a battalion.
 *
 * @generated from message anduril.entitymanager.v1.Echelon
 */
export declare type Echelon = Message<"anduril.entitymanager.v1.Echelon"> & {
  /**
   * @generated from oneof anduril.entitymanager.v1.Echelon.echelon_type
   */
  echelonType: {
    /**
     * @generated from field: anduril.entitymanager.v1.ArmyEchelon army_echelon = 1;
     */
    value: ArmyEchelon;
    case: "armyEchelon";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message anduril.entitymanager.v1.Echelon.
 * Use `create(EchelonSchema)` to create a new message.
 */
export declare const EchelonSchema: GenMessage<Echelon>;

/**
 * Military units defined by the Army.
 *
 * @generated from enum anduril.entitymanager.v1.ArmyEchelon
 */
export enum ArmyEchelon {
  /**
   * @generated from enum value: ARMY_ECHELON_INVALID = 0;
   */
  INVALID = 0,

  /**
   * Smallest unit group, e.g., a few soldiers
   *
   * @generated from enum value: ARMY_ECHELON_FIRE_TEAM = 1;
   */
  FIRE_TEAM = 1,

  /**
   * E.g., a group of fire teams
   *
   * @generated from enum value: ARMY_ECHELON_SQUAD = 2;
   */
  SQUAD = 2,

  /**
   * E.g., several squads
   *
   * @generated from enum value: ARMY_ECHELON_PLATOON = 3;
   */
  PLATOON = 3,

  /**
   * E.g., several platoons
   *
   * @generated from enum value: ARMY_ECHELON_COMPANY = 4;
   */
  COMPANY = 4,

  /**
   * E.g., several companies
   *
   * @generated from enum value: ARMY_ECHELON_BATTALION = 5;
   */
  BATTALION = 5,

  /**
   * E.g., several battalions
   *
   * @generated from enum value: ARMY_ECHELON_REGIMENT = 6;
   */
  REGIMENT = 6,

  /**
   * E.g., several regiments or battalions
   *
   * @generated from enum value: ARMY_ECHELON_BRIGADE = 7;
   */
  BRIGADE = 7,

  /**
   * E.g., several brigades
   *
   * @generated from enum value: ARMY_ECHELON_DIVISION = 8;
   */
  DIVISION = 8,

  /**
   * E.g., several divisions
   *
   * @generated from enum value: ARMY_ECHELON_CORPS = 9;
   */
  CORPS = 9,

  /**
   * E.g., several corps
   *
   * @generated from enum value: ARMY_ECHELON_ARMY = 10;
   */
  ARMY = 10,
}

/**
 * Describes the enum anduril.entitymanager.v1.ArmyEchelon.
 */
export declare const ArmyEchelonSchema: GenEnum<ArmyEchelon>;

