// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/group.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/group.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_group_pub: GenFile;

/**
 * Details related to grouping for this entity
 *
 * @generated from message anduril.entitymanager.v1.GroupDetails
 */
export declare type GroupDetails = Message<"anduril.entitymanager.v1.GroupDetails"> & {
};

/**
 * Describes the message anduril.entitymanager.v1.GroupDetails.
 * Use `create(GroupDetailsSchema)` to create a new message.
 */
export declare const GroupDetailsSchema: GenMessage<GroupDetails>;

