// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/group.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/entitymanager/v1/group.pub.proto.
 */
export const file_anduril_entitymanager_v1_group_pub = /*@__PURE__*/
  fileDesc("CihhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvZ3JvdXAucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEiDgoMR3JvdXBEZXRhaWxzQv4BChxjb20uYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxQg1Hcm91cFB1YlByb3RvUAFaTWdoZS5hbmR1cmlsLmRldi9hbmR1cmlsL2FuZHVyaWxhcGlzLWdvL2FuZHVyaWwvZW50aXR5bWFuYWdlci92MTtlbnRpdHltYW5hZ2VyogIDQUVYqgIYQW5kdXJpbC5FbnRpdHltYW5hZ2VyLlYxygIYQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYx4gIkQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYxXEdQQk1ldGFkYXRh6gIaQW5kdXJpbDo6RW50aXR5bWFuYWdlcjo6VjFiBnByb3RvMw");

/**
 * Describes the message anduril.entitymanager.v1.GroupDetails.
 * Use `create(GroupDetailsSchema)` to create a new message.
 */
export const GroupDetailsSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_group_pub, 0);

