// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/media.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_options_pub } from "./options.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/media.pub.proto.
 */
export const file_anduril_entitymanager_v1_media_pub = /*@__PURE__*/
  fileDesc("CihhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvbWVkaWEucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEiQAoFTWVkaWESNwoFbWVkaWEYASADKAsyIy5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuTWVkaWFJdGVtQgPIPgEiYgoJTWVkaWFJdGVtEgsKA3VybBgBIAEoCRIxCgR0eXBlGAIgASgOMiMuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLk1lZGlhVHlwZRIVCg1yZWxhdGl2ZV9wYXRoGAMgASgJKoYBCglNZWRpYVR5cGUSFgoSTUVESUFfVFlQRV9JTlZBTElEEAASGAoUTUVESUFfVFlQRV9USFVNQk5BSUwQARIUChBNRURJQV9UWVBFX0lNQUdFEAISFAoQTUVESUFfVFlQRV9WSURFTxADEhsKF01FRElBX1RZUEVfU0xJUFBZX1RJTEVTEARC/gEKHGNvbS5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjFCDU1lZGlhUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_anduril_entitymanager_v1_options_pub]);

/**
 * Describes the message anduril.entitymanager.v1.Media.
 * Use `create(MediaSchema)` to create a new message.
 */
export const MediaSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_media_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.MediaItem.
 * Use `create(MediaItemSchema)` to create a new message.
 */
export const MediaItemSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_media_pub, 1);

/**
 * Describes the enum anduril.entitymanager.v1.MediaType.
 */
export const MediaTypeSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_media_pub, 0);

/**
 * @generated from enum anduril.entitymanager.v1.MediaType
 */
export const MediaType = /*@__PURE__*/
  tsEnum(MediaTypeSchema);

