// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/notification.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Entity, Provenance } from "./entity.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/notification.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_notification_pub: GenFile;

/**
 * A notification to indicate when a field is overridden on an entity.
 *
 * @generated from message anduril.entitymanager.v1.OverrideNotificationPayload
 */
export declare type OverrideNotificationPayload = Message<"anduril.entitymanager.v1.OverrideNotificationPayload"> & {
  /**
   * The entity containing the values to override and the entityID being overriden.
   * Used by the client to determine the value a field is overridden to (e.g. hostile).
   *
   * @generated from field: anduril.entitymanager.v1.Entity entity = 1;
   */
  entity?: Entity;

  /**
   * The field path determining the path on an entity to override. Used by the client
   * to determine whether an override request was for a particular field (e.g. disposition).
   *
   * @generated from field: string field_path = 2;
   */
  fieldPath: string;

  /**
   * The provenance of the override request. This should always match the OverrideEntityRequest
   * provenance field.
   *
   * @generated from field: anduril.entitymanager.v1.Provenance provenance = 3;
   */
  provenance?: Provenance;
};

/**
 * Describes the message anduril.entitymanager.v1.OverrideNotificationPayload.
 * Use `create(OverrideNotificationPayloadSchema)` to create a new message.
 */
export declare const OverrideNotificationPayloadSchema: GenMessage<OverrideNotificationPayload>;

