// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/notification.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_entity_pub } from "./entity.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/notification.pub.proto.
 */
export const file_anduril_entitymanager_v1_notification_pub = /*@__PURE__*/
  fileDesc("Ci9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvbm90aWZpY2F0aW9uLnB1Yi5wcm90bxIYYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxIp0BChtPdmVycmlkZU5vdGlmaWNhdGlvblBheWxvYWQSMAoGZW50aXR5GAEgASgLMiAuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkVudGl0eRISCgpmaWVsZF9wYXRoGAIgASgJEjgKCnByb3ZlbmFuY2UYAyABKAsyJC5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuUHJvdmVuYW5jZUKFAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIUTm90aWZpY2F0aW9uUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_anduril_entitymanager_v1_entity_pub]);

/**
 * Describes the message anduril.entitymanager.v1.OverrideNotificationPayload.
 * Use `create(OverrideNotificationPayloadSchema)` to create a new message.
 */
export const OverrideNotificationPayloadSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_notification_pub, 0);

