// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/ontology.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Disposition, Environment, Nationality } from "../../ontology/v1/type.pub_pb.js";
import type { Template } from "./types.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/ontology.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_ontology_pub: GenFile;

/**
 * Available for Entities that have a military view representation.
 *
 * @generated from message anduril.entitymanager.v1.MilView
 */
export declare type MilView = Message<"anduril.entitymanager.v1.MilView"> & {
  /**
   * @generated from field: anduril.ontology.v1.Disposition disposition = 1;
   */
  disposition: Disposition;

  /**
   * @generated from field: anduril.ontology.v1.Environment environment = 2;
   */
  environment: Environment;

  /**
   * @generated from field: anduril.ontology.v1.Nationality nationality = 3;
   */
  nationality: Nationality;
};

/**
 * Describes the message anduril.entitymanager.v1.MilView.
 * Use `create(MilViewSchema)` to create a new message.
 */
export declare const MilViewSchema: GenMessage<MilView>;

/**
 * Ontology of the entity.
 *
 * @generated from message anduril.entitymanager.v1.Ontology
 */
export declare type Ontology = Message<"anduril.entitymanager.v1.Ontology"> & {
  /**
   * A string that describes the entity's high-level type with natural language.
   * Examples include "FIGHTER", "TANK", "AIRCRAFT CARRIER", "UAV".
   *
   * @generated from field: string platform_type = 3;
   */
  platformType: string;

  /**
   * A string that describes the entity's exact model or type.
   * Examples include "F-16", "NASAMS-LCHR", "ARLEIGH BURKE DDG", "GHOST".
   *
   * @generated from field: string specific_type = 4;
   */
  specificType: string;

  /**
   * The template used when creating this entity. Specifies minimum required components.
   *
   * @generated from field: anduril.entitymanager.v1.Template template = 2;
   */
  template: Template;
};

/**
 * Describes the message anduril.entitymanager.v1.Ontology.
 * Use `create(OntologySchema)` to create a new message.
 */
export declare const OntologySchema: GenMessage<Ontology>;

