// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/ontology.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_options_pub } from "./options.pub_pb.js";
import { file_anduril_entitymanager_v1_types_pub } from "./types.pub_pb.js";
import { file_anduril_ontology_v1_type_pub } from "../../ontology/v1/type.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/ontology.pub.proto.
 */
export const file_anduril_entitymanager_v1_ontology_pub = /*@__PURE__*/
  fileDesc("CithbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvb250b2xvZ3kucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEivQEKB01pbFZpZXcSOgoLZGlzcG9zaXRpb24YASABKA4yIC5hbmR1cmlsLm9udG9sb2d5LnYxLkRpc3Bvc2l0aW9uQgPIPgESOgoLZW52aXJvbm1lbnQYAiABKA4yIC5hbmR1cmlsLm9udG9sb2d5LnYxLkVudmlyb25tZW50QgPIPgESOgoLbmF0aW9uYWxpdHkYAyABKA4yIC5hbmR1cmlsLm9udG9sb2d5LnYxLk5hdGlvbmFsaXR5QgPIPgEiiwEKCE9udG9sb2d5EhoKDXBsYXRmb3JtX3R5cGUYAyABKAlCA8g+ARIaCg1zcGVjaWZpY190eXBlGAQgASgJQgPIPgESNAoIdGVtcGxhdGUYAiABKA4yIi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuVGVtcGxhdGVKBAgBEAJSC2Rlc2NyaXB0b3JzQoECChxjb20uYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxQhBPbnRvbG9neVB1YlByb3RvUAFaTWdoZS5hbmR1cmlsLmRldi9hbmR1cmlsL2FuZHVyaWxhcGlzLWdvL2FuZHVyaWwvZW50aXR5bWFuYWdlci92MTtlbnRpdHltYW5hZ2VyogIDQUVYqgIYQW5kdXJpbC5FbnRpdHltYW5hZ2VyLlYxygIYQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYx4gIkQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYxXEdQQk1ldGFkYXRh6gIaQW5kdXJpbDo6RW50aXR5bWFuYWdlcjo6VjFiBnByb3RvMw", [file_anduril_entitymanager_v1_options_pub, file_anduril_entitymanager_v1_types_pub, file_anduril_ontology_v1_type_pub]);

/**
 * Describes the message anduril.entitymanager.v1.MilView.
 * Use `create(MilViewSchema)` to create a new message.
 */
export const MilViewSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_ontology_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.Ontology.
 * Use `create(OntologySchema)` to create a new message.
 */
export const OntologySchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_ontology_pub, 1);

