// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/options.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv1";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/options.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_options_pub: GenFile;

/**
 * @generated from extension: bool overridable = 1001;
 */
export declare const overridable: GenExtension<FieldOptions, boolean>;

