// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/payloads.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Environment } from "../../ontology/v1/type.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/payloads.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_payloads_pub: GenFile;

/**
 * List of payloads available for an entity. i.e a weapon.
 *
 * @generated from message anduril.entitymanager.v1.Payloads
 */
export declare type Payloads = Message<"anduril.entitymanager.v1.Payloads"> & {
  /**
   * @generated from field: repeated anduril.entitymanager.v1.Payload payload_configurations = 1;
   */
  payloadConfigurations: Payload[];
};

/**
 * Describes the message anduril.entitymanager.v1.Payloads.
 * Use `create(PayloadsSchema)` to create a new message.
 */
export declare const PayloadsSchema: GenMessage<Payloads>;

/**
 * Individual payload configuration.
 *
 * @generated from message anduril.entitymanager.v1.Payload
 */
export declare type Payload = Message<"anduril.entitymanager.v1.Payload"> & {
  /**
   * @generated from field: anduril.entitymanager.v1.PayloadConfiguration config = 1;
   */
  config?: PayloadConfiguration;
};

/**
 * Describes the message anduril.entitymanager.v1.Payload.
 * Use `create(PayloadSchema)` to create a new message.
 */
export declare const PayloadSchema: GenMessage<Payload>;

/**
 * @generated from message anduril.entitymanager.v1.PayloadConfiguration
 */
export declare type PayloadConfiguration = Message<"anduril.entitymanager.v1.PayloadConfiguration"> & {
  /**
   * Identifying ID for the capability.
   * This ID may be used multiple times to represent payloads that are the same capability but have different operational states
   *
   * @generated from field: string capability_id = 1;
   */
  capabilityId: string;

  /**
   * The number of payloads currently available in the configuration.
   *
   * @generated from field: uint32 quantity = 4;
   */
  quantity: number;

  /**
   * The target environments the configuration is effective against.
   *
   * @generated from field: repeated anduril.ontology.v1.Environment effective_environment = 5;
   */
  effectiveEnvironment: Environment[];

  /**
   * The operational state of this payload.
   *
   * @generated from field: anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6;
   */
  payloadOperationalState: PayloadOperationalState;

  /**
   * A human readable description of the payload
   *
   * @generated from field: string payload_description = 7;
   */
  payloadDescription: string;
};

/**
 * Describes the message anduril.entitymanager.v1.PayloadConfiguration.
 * Use `create(PayloadConfigurationSchema)` to create a new message.
 */
export declare const PayloadConfigurationSchema: GenMessage<PayloadConfiguration>;

/**
 * Describes the current operational state of a payload configuration.
 *
 * @generated from enum anduril.entitymanager.v1.PayloadOperationalState
 */
export enum PayloadOperationalState {
  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_OFF = 1;
   */
  OFF = 1,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL = 2;
   */
  NON_OPERATIONAL = 2,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_DEGRADED = 3;
   */
  DEGRADED = 3,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_OPERATIONAL = 4;
   */
  OPERATIONAL = 4,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE = 5;
   */
  OUT_OF_SERVICE = 5,

  /**
   * @generated from enum value: PAYLOAD_OPERATIONAL_STATE_UNKNOWN = 6;
   */
  UNKNOWN = 6,
}

/**
 * Describes the enum anduril.entitymanager.v1.PayloadOperationalState.
 */
export declare const PayloadOperationalStateSchema: GenEnum<PayloadOperationalState>;

