// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/payloads.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_options_pub } from "./options.pub_pb.js";
import { file_anduril_ontology_v1_type_pub } from "../../ontology/v1/type.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/payloads.pub.proto.
 */
export const file_anduril_entitymanager_v1_payloads_pub = /*@__PURE__*/
  fileDesc("CithbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvcGF5bG9hZHMucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEiUgoIUGF5bG9hZHMSRgoWcGF5bG9hZF9jb25maWd1cmF0aW9ucxgBIAMoCzIhLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5QYXlsb2FkQgPIPgEiSQoHUGF5bG9hZBI+CgZjb25maWcYASABKAsyLi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuUGF5bG9hZENvbmZpZ3VyYXRpb24i8wEKFFBheWxvYWRDb25maWd1cmF0aW9uEhUKDWNhcGFiaWxpdHlfaWQYASABKAkSEAoIcXVhbnRpdHkYBCABKA0SPwoVZWZmZWN0aXZlX2Vudmlyb25tZW50GAUgAygOMiAuYW5kdXJpbC5vbnRvbG9neS52MS5FbnZpcm9ubWVudBJUChlwYXlsb2FkX29wZXJhdGlvbmFsX3N0YXRlGAYgASgOMjEuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlBheWxvYWRPcGVyYXRpb25hbFN0YXRlEhsKE3BheWxvYWRfZGVzY3JpcHRpb24YByABKAkqugIKF1BheWxvYWRPcGVyYXRpb25hbFN0YXRlEiUKIVBBWUxPQURfT1BFUkFUSU9OQUxfU1RBVEVfSU5WQUxJRBAAEiEKHVBBWUxPQURfT1BFUkFUSU9OQUxfU1RBVEVfT0ZGEAESLQopUEFZTE9BRF9PUEVSQVRJT05BTF9TVEFURV9OT05fT1BFUkFUSU9OQUwQAhImCiJQQVlMT0FEX09QRVJBVElPTkFMX1NUQVRFX0RFR1JBREVEEAMSKQolUEFZTE9BRF9PUEVSQVRJT05BTF9TVEFURV9PUEVSQVRJT05BTBAEEiwKKFBBWUxPQURfT1BFUkFUSU9OQUxfU1RBVEVfT1VUX09GX1NFUlZJQ0UQBRIlCiFQQVlMT0FEX09QRVJBVElPTkFMX1NUQVRFX1VOS05PV04QBkKBAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIQUGF5bG9hZHNQdWJQcm90b1ABWk1naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjE7ZW50aXR5bWFuYWdlcqICA0FFWKoCGEFuZHVyaWwuRW50aXR5bWFuYWdlci5WMcoCGEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMeICJEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMVxHUEJNZXRhZGF0YeoCGkFuZHVyaWw6OkVudGl0eW1hbmFnZXI6OlYxYgZwcm90bzM", [file_anduril_entitymanager_v1_options_pub, file_anduril_ontology_v1_type_pub]);

/**
 * Describes the message anduril.entitymanager.v1.Payloads.
 * Use `create(PayloadsSchema)` to create a new message.
 */
export const PayloadsSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_payloads_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.Payload.
 * Use `create(PayloadSchema)` to create a new message.
 */
export const PayloadSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_payloads_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.PayloadConfiguration.
 * Use `create(PayloadConfigurationSchema)` to create a new message.
 */
export const PayloadConfigurationSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_payloads_pub, 2);

/**
 * Describes the enum anduril.entitymanager.v1.PayloadOperationalState.
 */
export const PayloadOperationalStateSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_payloads_pub, 0);

/**
 * Describes the current operational state of a payload configuration.
 *
 * @generated from enum anduril.entitymanager.v1.PayloadOperationalState
 */
export const PayloadOperationalState = /*@__PURE__*/
  tsEnum(PayloadOperationalStateSchema);

