// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/power.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/power.pub.proto.
 */
export const file_anduril_entitymanager_v1_power_pub = /*@__PURE__*/
  fileDesc("CihhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvcG93ZXIucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEi2gEKClBvd2VyU3RhdGUSVQoSc291cmNlX2lkX3RvX3N0YXRlGAUgAygLMjkuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlBvd2VyU3RhdGUuU291cmNlSWRUb1N0YXRlRW50cnkaXQoUU291cmNlSWRUb1N0YXRlRW50cnkSCwoDa2V5GAEgASgJEjQKBXZhbHVlGAIgASgLMiUuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlBvd2VyU291cmNlOgI4AUoECAEQAkoECAIQA0oECAMQBEoECAQQBSKBAgoLUG93ZXJTb3VyY2USOwoMcG93ZXJfc3RhdHVzGAEgASgOMiUuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlBvd2VyU3RhdHVzEjcKCnBvd2VyX3R5cGUYAiABKA4yIy5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuUG93ZXJUeXBlEjkKC3Bvd2VyX2xldmVsGAMgASgLMiQuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLlBvd2VyTGV2ZWwSEAoIbWVzc2FnZXMYBCADKAkSLwoLb2ZmbG9hZGFibGUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuQm9vbFZhbHVlIq0CCgpQb3dlckxldmVsEhAKCGNhcGFjaXR5GAEgASgCEhEKCXJlbWFpbmluZxgCIAEoAhIZChFwZXJjZW50X3JlbWFpbmluZxgDIAEoAhItCgd2b2x0YWdlGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLkRvdWJsZVZhbHVlEjIKDGN1cnJlbnRfYW1wcxgFIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZRI8ChZydW5fdGltZV90b19lbXB0eV9taW5zGAYgASgLMhwuZ29vZ2xlLnByb3RvYnVmLkRvdWJsZVZhbHVlEj4KGGNvbnN1bXB0aW9uX3JhdGVfbF9wZXJfcxgHIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZSquAQoLUG93ZXJTdGF0dXMSGAoUUE9XRVJfU1RBVFVTX0lOVkFMSUQQABIYChRQT1dFUl9TVEFUVVNfVU5LTk9XThABEhwKGFBPV0VSX1NUQVRVU19OT1RfUFJFU0VOVBACEhoKFlBPV0VSX1NUQVRVU19PUEVSQVRJTkcQAxIZChVQT1dFUl9TVEFUVVNfRElTQUJMRUQQBBIWChJQT1dFUl9TVEFUVVNfRVJST1IQBSpnCglQb3dlclR5cGUSFgoSUE9XRVJfVFlQRV9JTlZBTElEEAASFgoSUE9XRVJfVFlQRV9VTktOT1dOEAESEgoOUE9XRVJfVFlQRV9HQVMQAhIWChJQT1dFUl9UWVBFX0JBVFRFUlkQA0L+AQocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUINUG93ZXJQdWJQcm90b1ABWk1naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjE7ZW50aXR5bWFuYWdlcqICA0FFWKoCGEFuZHVyaWwuRW50aXR5bWFuYWdlci5WMcoCGEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMeICJEFuZHVyaWxcRW50aXR5bWFuYWdlclxWMVxHUEJNZXRhZGF0YeoCGkFuZHVyaWw6OkVudGl0eW1hbmFnZXI6OlYxYgZwcm90bzM", [file_google_protobuf_wrappers]);

/**
 * Describes the message anduril.entitymanager.v1.PowerState.
 * Use `create(PowerStateSchema)` to create a new message.
 */
export const PowerStateSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_power_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.PowerSource.
 * Use `create(PowerSourceSchema)` to create a new message.
 */
export const PowerSourceSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_power_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.PowerLevel.
 * Use `create(PowerLevelSchema)` to create a new message.
 */
export const PowerLevelSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_power_pub, 2);

/**
 * Describes the enum anduril.entitymanager.v1.PowerStatus.
 */
export const PowerStatusSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_power_pub, 0);

/**
 * @generated from enum anduril.entitymanager.v1.PowerStatus
 */
export const PowerStatus = /*@__PURE__*/
  tsEnum(PowerStatusSchema);

/**
 * Describes the enum anduril.entitymanager.v1.PowerType.
 */
export const PowerTypeSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_power_pub, 1);

/**
 * @generated from enum anduril.entitymanager.v1.PowerType
 */
export const PowerType = /*@__PURE__*/
  tsEnum(PowerTypeSchema);

