// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/rate_limit.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/entitymanager/v1/rate_limit.pub.proto.
 */
export const file_anduril_entitymanager_v1_rate_limit_pub = /*@__PURE__*/
  fileDesc("Ci1hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvcmF0ZV9saW1pdC5wdWIucHJvdG8SGGFuZHVyaWwuZW50aXR5bWFuYWdlci52MSIvCglSYXRlTGltaXQSIgoadXBkYXRlX3Blcl9lbnRpdHlfbGltaXRfbXMYASABKA1CggIKHGNvbS5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjFCEVJhdGVMaW1pdFB1YlByb3RvUAFaTWdoZS5hbmR1cmlsLmRldi9hbmR1cmlsL2FuZHVyaWxhcGlzLWdvL2FuZHVyaWwvZW50aXR5bWFuYWdlci92MTtlbnRpdHltYW5hZ2VyogIDQUVYqgIYQW5kdXJpbC5FbnRpdHltYW5hZ2VyLlYxygIYQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYx4gIkQW5kdXJpbFxFbnRpdHltYW5hZ2VyXFYxXEdQQk1ldGFkYXRh6gIaQW5kdXJpbDo6RW50aXR5bWFuYWdlcjo6VjFiBnByb3RvMw");

/**
 * Describes the message anduril.entitymanager.v1.RateLimit.
 * Use `create(RateLimitSchema)` to create a new message.
 */
export const RateLimitSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_rate_limit_pub, 0);

