// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/route_details.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/route_details.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_route_details_pub: GenFile;

/**
 * @generated from message anduril.entitymanager.v1.RouteDetails
 */
export declare type RouteDetails = Message<"anduril.entitymanager.v1.RouteDetails"> & {
  /**
   * Free form text giving the name of the entity's destination
   *
   * @generated from field: string destination_name = 1;
   */
  destinationName: string;

  /**
   * Estimated time of arrival at destination
   *
   * @generated from field: google.protobuf.Timestamp estimated_arrival_time = 2;
   */
  estimatedArrivalTime?: Timestamp;
};

/**
 * Describes the message anduril.entitymanager.v1.RouteDetails.
 * Use `create(RouteDetailsSchema)` to create a new message.
 */
export declare const RouteDetailsSchema: GenMessage<RouteDetails>;

