// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/route_details.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/route_details.pub.proto.
 */
export const file_anduril_entitymanager_v1_route_details_pub = /*@__PURE__*/
  fileDesc("CjBhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvcm91dGVfZGV0YWlscy5wdWIucHJvdG8SGGFuZHVyaWwuZW50aXR5bWFuYWdlci52MSJkCgxSb3V0ZURldGFpbHMSGAoQZGVzdGluYXRpb25fbmFtZRgBIAEoCRI6ChZlc3RpbWF0ZWRfYXJyaXZhbF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEKFAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIUUm91dGVEZXRhaWxzUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message anduril.entitymanager.v1.RouteDetails.
 * Use `create(RouteDetailsSchema)` to create a new message.
 */
export const RouteDetailsSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_route_details_pub, 0);

