// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/schedule.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/entitymanager/v1/schedule.pub.proto.
 */
export const file_anduril_entitymanager_v1_schedule_pub = /*@__PURE__*/
  fileDesc("CithbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvc2NoZWR1bGUucHViLnByb3RvEhhhbmR1cmlsLmVudGl0eW1hbmFnZXIudjEiQgoJU2NoZWR1bGVzEjUKCXNjaGVkdWxlcxgBIAMoCzIiLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5TY2hlZHVsZSKVAQoIU2NoZWR1bGUSNQoHd2luZG93cxgBIAMoCzIkLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5Dcm9uV2luZG93EhMKC3NjaGVkdWxlX2lkGAIgASgJEj0KDXNjaGVkdWxlX3R5cGUYAyABKA4yJi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuU2NoZWR1bGVUeXBlIj4KCkNyb25XaW5kb3cSFwoPY3Jvbl9leHByZXNzaW9uGAEgASgJEhcKD2R1cmF0aW9uX21pbGxpcxgCIAEoBCpuCgxTY2hlZHVsZVR5cGUSGQoVU0NIRURVTEVfVFlQRV9JTlZBTElEEAASHgoaU0NIRURVTEVfVFlQRV9aT05FX0VOQUJMRUQQARIjCh9TQ0hFRFVMRV9UWVBFX1pPTkVfVEVNUF9FTkFCTEVEEAJCgQIKHGNvbS5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjFCEFNjaGVkdWxlUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z");

/**
 * Describes the message anduril.entitymanager.v1.Schedules.
 * Use `create(SchedulesSchema)` to create a new message.
 */
export const SchedulesSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_schedule_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_schedule_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.CronWindow.
 * Use `create(CronWindowSchema)` to create a new message.
 */
export const CronWindowSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_schedule_pub, 2);

/**
 * Describes the enum anduril.entitymanager.v1.ScheduleType.
 */
export const ScheduleTypeSchema = /*@__PURE__*/
  enumDesc(file_anduril_entitymanager_v1_schedule_pub, 0);

/**
 * The type of Schedule.
 *
 * @generated from enum anduril.entitymanager.v1.ScheduleType
 */
export const ScheduleType = /*@__PURE__*/
  tsEnum(ScheduleTypeSchema);

