// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/target_priority.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_options_pub } from "./options.pub_pb.js";

/**
 * Describes the file anduril/entitymanager/v1/target_priority.pub.proto.
 */
export const file_anduril_entitymanager_v1_target_priority_pub = /*@__PURE__*/
  fileDesc("CjJhbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvdGFyZ2V0X3ByaW9yaXR5LnB1Yi5wcm90bxIYYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxIo0BCg5UYXJnZXRQcmlvcml0eRJJChFoaWdoX3ZhbHVlX3RhcmdldBgBIAEoCzIpLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5IaWdoVmFsdWVUYXJnZXRCA8g+ARIwCgZ0aHJlYXQYAiABKAsyIC5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuVGhyZWF0Iq8BCg9IaWdoVmFsdWVUYXJnZXQSHAoUaXNfaGlnaF92YWx1ZV90YXJnZXQYASABKAgSFwoPdGFyZ2V0X3ByaW9yaXR5GAIgASgNEkYKDnRhcmdldF9tYXRjaGVzGAMgAygLMi4uYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLkhpZ2hWYWx1ZVRhcmdldE1hdGNoEh0KFWlzX2hpZ2hfcGF5b2ZmX3RhcmdldBgEIAEoCCJjChRIaWdoVmFsdWVUYXJnZXRNYXRjaBIhChloaWdoX3ZhbHVlX3RhcmdldF9saXN0X2lkGAEgASgJEigKIGhpZ2hfdmFsdWVfdGFyZ2V0X2Rlc2NyaXB0aW9uX2lkGAIgASgJIhsKBlRocmVhdBIRCglpc190aHJlYXQYASABKAhChwIKHGNvbS5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjFCFlRhcmdldFByaW9yaXR5UHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_anduril_entitymanager_v1_options_pub]);

/**
 * Describes the message anduril.entitymanager.v1.TargetPriority.
 * Use `create(TargetPrioritySchema)` to create a new message.
 */
export const TargetPrioritySchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_target_priority_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.HighValueTarget.
 * Use `create(HighValueTargetSchema)` to create a new message.
 */
export const HighValueTargetSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_target_priority_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.HighValueTargetMatch.
 * Use `create(HighValueTargetMatchSchema)` to create a new message.
 */
export const HighValueTargetMatchSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_target_priority_pub, 2);

/**
 * Describes the message anduril.entitymanager.v1.Threat.
 * Use `create(ThreatSchema)` to create a new message.
 */
export const ThreatSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_target_priority_pub, 3);

