// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/entitymanager/v1/transponder_codes.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/transponder_codes.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_transponder_codes_pub: GenFile;

/**
 * A message describing any transponder codes associated with Mode 1, 2, 3, 4, 5, S interrogations.
 *
 * @generated from message anduril.entitymanager.v1.TransponderCodes
 */
export declare type TransponderCodes = Message<"anduril.entitymanager.v1.TransponderCodes"> & {
  /**
   * The mode 1 code assigned to military assets.
   *
   * @generated from field: uint32 mode1 = 1;
   */
  mode1: number;

  /**
   * The Mode 2 code assigned to military assets.
   *
   * @generated from field: uint32 mode2 = 2;
   */
  mode2: number;

  /**
   * The Mode 3 code assigned by ATC to the asset.
   *
   * @generated from field: uint32 mode3 = 3;
   */
  mode3: number;

  /**
   * The validity of the response from the Mode 4 interrogation.
   *
   * @generated from field: anduril.entitymanager.v1.InterrogationResponse mode4_interrogation_response = 4;
   */
  mode4InterrogationResponse: InterrogationResponse;

  /**
   * The Mode 5 transponder codes.
   *
   * @generated from field: anduril.entitymanager.v1.Mode5 mode5 = 5;
   */
  mode5?: Mode5;

  /**
   * The Mode S transponder codes.
   *
   * @generated from field: anduril.entitymanager.v1.ModeS mode_s = 6;
   */
  modeS?: ModeS;
};

/**
 * Describes the message anduril.entitymanager.v1.TransponderCodes.
 * Use `create(TransponderCodesSchema)` to create a new message.
 */
export declare const TransponderCodesSchema: GenMessage<TransponderCodes>;

/**
 * Describes the Mode 5 transponder interrogation status and codes.
 *
 * @generated from message anduril.entitymanager.v1.Mode5
 */
export declare type Mode5 = Message<"anduril.entitymanager.v1.Mode5"> & {
  /**
   * The validity of the response from the Mode 5 interrogation.
   *
   * @generated from field: anduril.entitymanager.v1.InterrogationResponse mode5_interrogation_response = 1;
   */
  mode5InterrogationResponse: InterrogationResponse;

  /**
   * The Mode 5 code assigned to military assets.
   *
   * @generated from field: uint32 mode5 = 2;
   */
  mode5: number;

  /**
   * The Mode 5 platform identification code.
   *
   * @generated from field: uint32 mode5_platform_id = 3;
   */
  mode5PlatformId: number;
};

/**
 * Describes the message anduril.entitymanager.v1.Mode5.
 * Use `create(Mode5Schema)` to create a new message.
 */
export declare const Mode5Schema: GenMessage<Mode5>;

/**
 * Describes the Mode S codes.
 *
 * @generated from message anduril.entitymanager.v1.ModeS
 */
export declare type ModeS = Message<"anduril.entitymanager.v1.ModeS"> & {
  /**
   * Mode S identifier which comprises of 8 alphanumeric characters.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The Mode S ICAO aircraft address. Expected values are between 1 and 16777214 decimal. The Mode S address is
   * considered unique.
   *
   * @generated from field: uint32 address = 2;
   */
  address: number;
};

/**
 * Describes the message anduril.entitymanager.v1.ModeS.
 * Use `create(ModeSSchema)` to create a new message.
 */
export declare const ModeSSchema: GenMessage<ModeS>;

/**
 * Indicates the interrogation status of a target.
 *
 * @generated from enum anduril.entitymanager.v1.InterrogationResponse
 */
export enum InterrogationResponse {
  /**
   * Note that INTERROGATION_INVALID indicates that the target has not been interrogated.
   *
   * @generated from enum value: INTERROGATION_RESPONSE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: INTERROGATION_RESPONSE_CORRECT = 1;
   */
  CORRECT = 1,

  /**
   * @generated from enum value: INTERROGATION_RESPONSE_INCORRECT = 2;
   */
  INCORRECT = 2,

  /**
   * @generated from enum value: INTERROGATION_RESPONSE_NO_RESPONSE = 3;
   */
  NO_RESPONSE = 3,
}

/**
 * Describes the enum anduril.entitymanager.v1.InterrogationResponse.
 */
export declare const InterrogationResponseSchema: GenEnum<InterrogationResponse>;

