// @generated by protoc-gen-es v2.2.0 with parameter "import_extension=js"
// @generated from file anduril/tasks/ad/desertguardian/common/v1/common_tasks.pub.proto (package anduril.tasks.ad.desertguardian.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/tasks/ad/desertguardian/common/v1/common_tasks.pub.proto.
 */
export declare const file_anduril_tasks_ad_desertguardian_common_v1_common_tasks_pub: GenFile;

/**
 * Set the power state of a Platform. It is up to the Platform to interpret the power state and act accordingly.
 *
 * @generated from message anduril.tasks.ad.desertguardian.common.v1.SetPowerState
 */
export declare type SetPowerState = Message<"anduril.tasks.ad.desertguardian.common.v1.SetPowerState"> & {
  /**
   * @generated from field: anduril.tasks.ad.desertguardian.common.v1.PowerState power_state = 1;
   */
  powerState: PowerState;
};

/**
 * Describes the message anduril.tasks.ad.desertguardian.common.v1.SetPowerState.
 * Use `create(SetPowerStateSchema)` to create a new message.
 */
export declare const SetPowerStateSchema: GenMessage<SetPowerState>;

/**
 * Delete an entity from the internal tracker of a Platform.
 * Does not silence or suppress the track from re-forming if the tracking conditions are satisfied.
 *
 * @generated from message anduril.tasks.ad.desertguardian.common.v1.DeleteTrack
 */
export declare type DeleteTrack = Message<"anduril.tasks.ad.desertguardian.common.v1.DeleteTrack"> & {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId: string;
};

/**
 * Describes the message anduril.tasks.ad.desertguardian.common.v1.DeleteTrack.
 * Use `create(DeleteTrackSchema)` to create a new message.
 */
export declare const DeleteTrackSchema: GenMessage<DeleteTrack>;

/**
 * Set this entity as a "High Priority Track".
 * The tasked Platform is responsible for maintaining a list of current High-Priority tracks.
 *
 * @generated from message anduril.tasks.ad.desertguardian.common.v1.SetHighPriorityTrack
 */
export declare type SetHighPriorityTrack = Message<"anduril.tasks.ad.desertguardian.common.v1.SetHighPriorityTrack"> & {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId: string;
};

/**
 * Describes the message anduril.tasks.ad.desertguardian.common.v1.SetHighPriorityTrack.
 * Use `create(SetHighPriorityTrackSchema)` to create a new message.
 */
export declare const SetHighPriorityTrackSchema: GenMessage<SetHighPriorityTrack>;

/**
 * Unset this entity as a "High Priority Track".
 * The tasked Platform is responsible for maintaining a list of current High-Priority tracks.
 *
 * @generated from message anduril.tasks.ad.desertguardian.common.v1.RemoveHighPriorityTrack
 */
export declare type RemoveHighPriorityTrack = Message<"anduril.tasks.ad.desertguardian.common.v1.RemoveHighPriorityTrack"> & {
  /**
   * @generated from field: string entity_id = 1;
   */
  entityId: string;
};

/**
 * Describes the message anduril.tasks.ad.desertguardian.common.v1.RemoveHighPriorityTrack.
 * Use `create(RemoveHighPriorityTrackSchema)` to create a new message.
 */
export declare const RemoveHighPriorityTrackSchema: GenMessage<RemoveHighPriorityTrack>;

/**
 * @generated from enum anduril.tasks.ad.desertguardian.common.v1.PowerState
 */
export enum PowerState {
  /**
   * @generated from enum value: POWER_STATE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: POWER_STATE_ON = 1;
   */
  ON = 1,

  /**
   * @generated from enum value: POWER_STATE_OFF = 2;
   */
  OFF = 2,
}

/**
 * Describes the enum anduril.tasks.ad.desertguardian.common.v1.PowerState.
 */
export declare const PowerStateSchema: GenEnum<PowerState>;

