// This file was auto-generated by Fern from our API Definition.

import * as Lattice from "../index.js";

export interface AgentRequest {
    executeRequest?: Lattice.ExecuteRequest;
    cancelRequest?: Lattice.CancelRequest;
    completeRequest?: Lattice.CompleteRequest;
}
