/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Lattice from "../index.js";

/**
 * Available for any Entities with alternate ids in other systems.
 */
export interface Aliases {
    alternateIds?: Lattice.AlternateId[];
    /** The best available version of the entity's display name. */
    name?: string;
}
