/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Lattice from "../index.js";

/**
 * Allocation contains a list of agents allocated to a Task.
 */
export interface Allocation {
    /** Agents actively being utilized in a Task. */
    activeAgents?: Lattice.Agent[];
}
