// This file was auto-generated by Fern from our API Definition.

import * as Lattice from "../index.js";

/**
 * Request to Cancel a Task.
 */
export interface CancelRequest {
    /** ID of the Task to cancel. */
    taskId?: string;
    /**
     * The assignee of the Task. Useful for agent routing where an endpoint owns multiple agents,
     *  especially onBehalfOf assignees.
     */
    assignee?: Lattice.Principal;
}
