/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EntityStreamHeartbeat {
    data: EntityStreamHeartbeat.Data;
}

export namespace EntityStreamHeartbeat {
    export interface Data {
        /** timestamp of the heartbeat */
        timestamp?: string;
    }
}
