// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Request to execute a Task.
 */
export interface ExecuteRequest {
    /** Task to execute. */
    task?: Lattice.Task;
}
