/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Lattice from "../index.js";

/**
 * Details related to grouping for this entity
 */
export interface GroupDetails {
    team?: Lattice.Team;
    echelon?: Lattice.Echelon;
}
