// This file was auto-generated by Fern from our API Definition.

import * as Lattice from "../index.js";

/**
 * The relationship component indicates a relationship to another entity.
 */
export interface Relationship {
    /** The entity ID to which this entity is related. */
    relatedEntityId?: string;
    /** A unique identifier for this relationship. Allows removing or updating relationships. */
    relationshipId?: string;
    /** The relationship type */
    relationshipType?: Lattice.RelationshipType;
}
