/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Lattice from "../index.js";

/**
 * Symbology associated with an entity.
 */
export interface Symbology {
    milStd2525C?: Lattice.MilStd2525C;
}
