/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Symmetric 3d matrix only representing the upper right triangle.
 */
export interface TMat3 {
    mxx?: number;
    mxy?: number;
    mxz?: number;
    myy?: number;
    myz?: number;
    mzz?: number;
}
