/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Lattice from "../../../index.js";

/**
 * stream event response.
 */
export type SseEntityEventsResponse =
    | Lattice.SseEntityEventsResponse.Heartbeat
    | Lattice.SseEntityEventsResponse.Entity;

export namespace SseEntityEventsResponse {
    export interface Heartbeat extends Lattice.EntityStreamHeartbeat {
        event: "heartbeat";
    }

    export interface Entity extends Lattice.EntityStreamEvent {
        event: "entity";
    }
}
