// This file was auto-generated by Fern from our API Definition.

import * as Lattice from "../../../index.js";

/**
 * The stream event response.
 */
export type StreamEntitiesResponse = Lattice.StreamEntitiesResponse.Heartbeat | Lattice.StreamEntitiesResponse.Entity;

export namespace StreamEntitiesResponse {
    export interface Heartbeat extends Lattice.EntityStreamHeartbeat {
        event: "heartbeat";
    }

    export interface Entity extends Lattice.EntityStreamEvent {
        event: "entity";
    }
}
