// This file was auto-generated by Fern from our API Definition.

export const GetObjectRequestAcceptEncoding = {
    Identity: "identity",
    Zstd: "zstd",
} as const;
export type GetObjectRequestAcceptEncoding =
    (typeof GetObjectRequestAcceptEncoding)[keyof typeof GetObjectRequestAcceptEncoding];
