/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetObjectRequestAcceptEncoding = "identity" | "zstd";
export const GetObjectRequestAcceptEncoding = {
    Identity: "identity",
    Zstd: "zstd",
} as const;
