// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import * as environments from "./environments.js";
import { Entities } from "./api/resources/entities/client/Client.js";
import { Tasks } from "./api/resources/tasks/client/Client.js";
import { Objects } from "./api/resources/objects/client/Client.js";

export declare namespace LatticeClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LatticeClient {
    protected readonly _options: LatticeClient.Options;
    protected _entities: Entities | undefined;
    protected _tasks: Tasks | undefined;
    protected _objects: Objects | undefined;

    constructor(_options: LatticeClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@anduril-industries/lattice-sdk",
                    "X-Fern-SDK-Version": "2.4.1",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get entities(): Entities {
        return (this._entities ??= new Entities(this._options));
    }

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this._options));
    }

    public get objects(): Objects {
        return (this._objects ??= new Objects(this._options));
    }
}
