// This file was auto-generated by Fern from our API Definition.

export const LatticeEnvironment = {
    Default: "https://example.developer.anduril.com",
} as const;

export type LatticeEnvironment = typeof LatticeEnvironment.Default;
